apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dashboard-server
  namespace: waziup
  labels:
    name: dashboard-server
spec:
  replicas: 1 
  template:
    metadata:
      name: dashboard-server
      labels:
        app: dashboard-server
    spec:
      containers:
      - name: dashboard-server
        image: waziup/dashboard-server:latest
        ports:
        - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: dashboard-server
  name: dashboard-server
  namespace: waziup
spec:
  type: NodePort
  ports:
    - port: 4000
      nodePort: 30025
  selector:
    app: dashboard-server

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dashboard-server
  namespace: waziup
spec:
  rules:
  - host: dashboardserver.waziup.io
    http:
      paths:
      - path: /
        backend:
          serviceName: dashboard-server
          servicePort: 4000
